export interface UserConfig {
    my_call: string,
    my_grid6: string,
    default_pwr: number,
    flr_host: string,
    flr_port: number,
    adif_host: string,
    adif_port: number,
    logger_type: number,
    size_x: number,
    size_y: number,
    is_max: boolean,
    cw_mode: string,
    ftx_mode: string,
    qth_string: string,
    rig_if_type: string,
    scan_wait_time: number,
    prop_enabled: boolean,
    prop_data_source: string,
    prop_refresh_minutes: number,
    prop_ssb_threshold: number,
    prop_digital_threshold: number,
    prop_distance_scale_km: number,
    prop_azimuth_scale_deg: number,
    prop_history_minutes: number,
}

export interface ConfigVer2 {
    id: string,
    key: string,
    val: string,
    type: string,
    enabled: boolean,
    editable: boolean,
    description: string,
    group: string,
}
